### ISSUE TITLE
Standardizing `from pyspark.sql import functions as F`

### ISSUE THREAD

**Issue by AbdealiLoKo** [joaopalmeiro/flake8-import-conventions#23]
Would be nice to standardize usage of `pyspark.sql.functions as F` and `pyspark.sql.types as T`

**Comment by joaopalmeiro** [comment]
Hi, @AbdealiLoKo!

Thank you for your suggestion, and sorry for the HUGE delay in responding! 

I will close this issue without implementing your suggestion because your suggestion, although I have used it in the past, does not seem a _standard_ to me (after looking for example at the [documentation](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/functions.html) and the [repo](https://github.com/search?q=repo%3Aapache%2Fspark%20pyspark.sql.functions&type=code) itself).
